#!/usr/bin/env sh
# some sort of power menu

choice="$(printf '%s\n%s\n%s' 'Poweroff' 'Reboot' 'Cancel' |
    dmenu -i -p 'Turn off PC? ')"

case "$choice" in
"Poweroff")
    poweroff
    ;;
"Reboot")
    reboot
    ;;
*)
    exit 0
    ;;
esac
