#!/usr/bin/env sh
# some sort of power menu

choices='Poweroff\nReboot\nCancel'
choice="$(printf "$choices" | dmenu -i -p 'Turn off PC? ')"

case "$choice" in
"Poweroff")
    poweroff
    ;;
"Reboot")
    reboot
    ;;
*)
    exit 0
    ;;
esac
